### ISSUE TITLE
Using with NPM and iojs causes NPM Err but works fine

### ISSUE THREAD

**Issue by OllieJennings** [pgilad/leasot#10]
![screen shot 2015-05-25 at 12 37 55](https://cloud.githubusercontent.com/assets/1575448/7796777/ed77127e-02da-11e5-9bce-c5bd7e0d0371.png)

I am not sure if this is intended or not as the apparent fault is the exit status of 1

**Comment by pgilad** [comment]
Intended results, yes. Desired results, perhaps not.

The exit code is 1 if any todos/fixmes are found, but that may not be the best handling. I thought it would be like jshint/jslint where they exit with an error code if any lint errors are found.

Relevant code: https://github.com/pgilad/leasot/blob/master/bin/leasot.js#L64-L70

Thoughts?

**Comment by OllieJennings** [comment]
Yeah l completely agree with you on the fact that it should behave like jshint/lint and maybe the way l was intending to use it, it not really the right way.

Only thought could be to add an option that "ignores errors", in the sense that if there are todos, it just exits with 0 anyways?

**Comment by pgilad** [comment]
I looked over some of the linter projects, and saw that they mostly exit with:
1. `0` - No lint errors found
2. `1` - Unpredicted error
3. `2` - Lint errors found (or sometimes returned as exit code `1)

jshint:
https://github.com/jshint/jshint/blob/928f19dbf3378734ef2119689dc51acfa37edfc2/src/cli.js#L728-L734

eslint:
https://github.com/eslint/eslint/blob/master/lib/cli.js#L184-L188

jscs:
https://github.com/jscs-dev/node-jscs/blob/master/lib/cli.js#L136-L150

None of them provide a clean exit code if lint errors were found.
What do you think?

A possible hack I can think of to fake the exit code is:
`least */*.js || true`

**Comment by OllieJennings** [comment]
I agree with what you have found in the other projects, l would keep the exit code 1. It makes sense, if there are any TODOs or FIXMES then it should error, as you don't really want any code with these in, to go into production.

I think the hack is perfectly fine to use in development.
