### ISSUE TITLE
How to use with VSCode?

### ISSUE THREAD

**Issue by mikeerickson** [pgilad/leasot#101]
I can see that one can use VSCode as the reporter, but I cant seem to figure out how to use it with vscode.   Is it only customizing the link (but still needs an output file)?

I am sure there is something basic I am missing (or am expecting it to do something it is not designed to do)

Assuming I execute from VSCode integrated terminal, what should I *expect*

```bash
> leasot ./server/**/*.*s -r vscode
```

**Comment by pgilad** [comment]
I actually never used it within vscode, maybe @SeanSobey would know?

**Comment by mikeerickson** [comment]
@SeanSobey @pgilad I have managed to put some things together to make it work pretty well

I am using [terminal markdown -- mdv](https://github.com/axiros/terminal_markdown_viewer#installation) and the following script 

```bash
> leasot -x './client/**/*.*s*' --tags review -r vscode > TODO.md && mdv TODO.md
```

This is a fair enough workflow

**Comment by mikeerickson** [comment]
@SeanSobey @pgilad 

On closer look, this is actually not working (the link opens the file, but doesnt jump to the line).  If I open the resulting markdown file within VSCode, they are correctly navigating properly.  I would rather not have to open the file in the editor, but instead display in the integrated terminal, or the output pane.

**Comment by SeanSobey** [comment]
I am using leasot via gulp, [gulp-todo](https://www.npmjs.com/package/gulp-todo) and a custom reporter implementation to work in the console. Here is a simplified version:

```js
const gulp = require('gulp');
const path = require('path');
const log = require('fancy-log');
const todo = require('gulp-todo');

gulp.task('todo', (done) => {
	
	let todoCount = 0;
	const appSrcPath = './src/';
	return gulp.src(appSrcPath + '**/*.js')
		.pipe(todo())
		.pipe(todo.reporter('vscode', {
			fileName: 'todo.md',
			transformComment: (file, line, text, kind, ref) => {
				todoCount++;
				if (ref) {
					text = `@${ref} ${text}`;
				}
				const fileName = path.join(appSrcPath, file);
				const filePath = path.resolve(appSrcPath, file);
				log(`${fileName}:${line} | ${text}`);
				return [`| [${fileName}](${filePath}#L${line}) | ${line} | ${text}`];
			}
		}))
        .pipe(gulp.dest('./'));
});
```
This will create a TODO.md and print in the console as well, eg:
```
[20:32:47] src\Utils\MomentRange.js:27 | We really need specs for this
```

The only really important line here is `log(`${fileName}:${line} | ${text}`);`, this is the console format used by vscode to link to a file as well as line (full spec being `file:line:column`).

You could achieve the same using a simple node script and the leasot programmatic API also, gulp is just a convenience for our implementation.

**Comment by mikeerickson** [comment]
@SeanSobey thank you for your feedback, I will have a closer look over the weekend.
