### ISSUE TITLE
Running `leasot -S -i node_modules *.js` doesn't ignore the node_modules folder.

### ISSUE THREAD

**Issue by tjimsk** [pgilad/leasot#107]
Shouldn't this work?

I'm at the parent directory of `node_modules` and I've tried the following, no luck.

`leasot -S -i node_modules/* *.js`
`leasot -S -i ./node_modules/* *.js`

version: 7.0.0-rc.5

**Comment by pgilad** [comment]
Are you trying to ignore node_modules? Can you use the following syntax:
`leasot -S -i 'node_modules/**/*' *.js` ?

**Comment by tjimsk** [comment]
Running `leasot -S -i node_modules/**/* *.js` still includes TODO's from the node_modules folder.  

To be clear, I am trying to ignore everything inside the node_modules directory.

**Comment by pgilad** [comment]
Yep, makes sense, can you try wrapping `node_modules/**/*` with single quotes ?

**Comment by tjimsk** [comment]
That works.  

Are there cases where simply doing `node_modules` or `node_modules/*` should not be a match?  Would that be a valid PR?  If so I can take a look at the code later.

**Comment by pgilad** [comment]
Hmm, good question, it probably makes sense to make it default, and the user can always explicitly add it, or another option to dis-regard all defaults

**Comment by tjimsk** [comment]
My comment was more concerning the need for single-quoting the expression to ignore.  CLI expects everything to be strings.

**Comment by pgilad** [comment]
@tjimsk What do you think?

**Comment by tjimsk** [comment]
The command is:

`leasot --ignore _ignoreArgs_ _args_

UX-wise, _args_ should evaluate recursively (including directories).  _ignoreArgs_ should be a pattern evaluated against each entry.  Directories matching _ignoreArgs_ are ignored and all their children.  I suppose the problem you mentioned about _ignoreArgs_ being expanded is a problem with the flag parsing package you're using.

**Comment by pgilad** [comment]
This is the current code that handles the pattern, would love it if you can help debug/investigate how to fix this issue! I'm sure it bothers other users as wel

**Comment by tjimsk** [comment]
@pgilad https://github.com/pgilad/leasot/pull/108 submitted

**Comment by pgilad** [comment]
Published fix under https://github.com/pgilad/leasot/releases/tag/v7.0.0-rc.6
