### ISSUE TITLE
feature request: support DONE keyword.

### ISSUE THREAD

**Issue by sramam** [pgilad/leasot#112]
Currently, I use leasot extensively to annotate work remaining to be done in my code base.
One pain that I feel is that the only way to get things "done" is to remove the annotation from the code base.

I understand that we can add our own key-words, but the idea of a special keyword "DONE", 
is to provide special formatting - ideally strike-through text is especially appealing.

At the risk of complicating the code base, I think this would be a great addition to leasot.

Before I go implementing anything, thoughts?

**Comment by pgilad** [comment]
I think this can already be done using a custom markdown reporter or at least overriding the body transforming func of it- conditionally on the tag key- output the dashes

**Comment by pgilad** [comment]
This is what you want to configure:
https://pgilad.github.io/leasot/index.html#transformcomment

**Comment by sramam** [comment]
thanks for the pointer.

Am I understanding this correctly, that one would have to create separate reporter in the core repo?
The CLI does not seem to offer a way to pass in the path to a custom reporter via the CLI.

Guessing the modified CLI would look like `--custom-reporter="/path/to/reporter"` or some such. 
But now it's starting to mess with the really clean API and usage of leasot. 

I'll just use custom tags and close this issue. Can revisit if there is more interest. 

Thanks for the great package btw. I have started to rely on it for a significant portion of WIP tasks.
