### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by yuhr** [pgilad/leasot#137]
Can you add F# support? F# has `// ...` for single-line and `(* ... *)` for multi-line.

Note that F# multi-line comments can be nested and it's great if leasot detects such nested TODOs.

**Comment by pgilad** [comment]
Welcome to add an addition! I've been told it's pretty easy :)

**Comment by pgilad** [comment]
So what do you say @yuhr - want to take a shot at adding support for F# ?
