### ISSUE TITLE
Vue.js: Only HTML comments register

### ISSUE THREAD

**Issue by selfagency** [pgilad/leasot#154]
```
vue-gridjs on  master [!?] is 📦 v0.1.4 via ⬢ v12.18.0 on ☁️  us-east-1
❯ leasot './src/**/*'


 ✔ No todos/fixmes found

vue-gridjs on  master [!?] is 📦 v0.1.4 via ⬢ v12.18.0 on ☁️  us-east-1
❯ leasot './src/**/*'

./src/vue-gridjs.vue
  line 2  TODO  Figure out a way to scope CSS to the component rather than the global scope

 ✖ 1 todo/fixme found
```

When I run Leasot on a folder containing `.vue` files, any comments in either the `<script>` or `<style>` portions of the code are ignored. Only comments in the HTML `<template>` area are registered by the CLI. The above shows output of a JavaScript comment (`// TODO`) vs. an HTML comment (`<!-- TODO -->`).

**Comment by selfagency** [comment]
closing this because it's 2 years old, the maintainer never responded, and i want to clean up my issues tab

**Comment by pgilad** [comment]
Have you tried --inline-files? As per in the readme?
