### ISSUE TITLE
Some broken edge cases in JavaScript files

### ISSUE THREAD

**Issue by Pharb** [pgilad/leasot#16]
A few edge cases in JavaScript seem not to be working as expected:

Input | Expected | Actual
--------|--------------|---------
`// TODO` | TODO found with text as empty string | No TODO found
`/* TODO */` | TODO found with text as empty string | TODO found with text "*"
`/*TODO text */` | TODO found with text "text" | No TODO found

**Comment by pgilad** [comment]
Yeah I agree, those are being parsed wrong. Need to tweak the regex (Perhaps relevant for all other parsers as well, #12 )
