### ISSUE TITLE
11.2 Cannot find module

### ISSUE THREAD

**Issue by bytestream** [pgilad/leasot#162]
Since 11.2 the following has stopped working, there was no such issue on 11.1:

```
$ npm install --global leasot
/usr/local/bin/leasot -> /usr/local/lib/node_modules/leasot/bin/leasot
/usr/local/bin/leasot-reporter -> /usr/local/lib/node_modules/leasot/bin/leasot-reporter
+ leasot@11.2.0
added 41 packages from 40 contributors in 2.512s
$ leasot -S '**/*.php' '**/*.js' --ignore 'node_modules/**/*','vendor/**/*' | tee leasot.txt
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module '../dist/cli/leasot.js'
```

Any ideas?

**Comment by pgilad** [comment]
Thanks for the report, I see it too, will work on a fix shortly

**Comment by pgilad** [comment]
Fixed in v11.3.0 - sorry about that, looks like something went wrong with the publish step on the previous version, hopefully won't happen again.

**Comment by pgilad** [comment]
Also deprecated the version in npm
![image](https://user-images.githubusercontent.com/4533329/91804255-f1a79380-ec33-11ea-9fd8-4bfaab8afe97.png)

**Comment by bytestream** [comment]
Thanks man 🚀🙌
