### ISSUE TITLE
11.6.0 should've been a major release

### ISSUE THREAD

**Issue by homer0** [pgilad/leasot#175]
Hi 👋!

First, amazing tool 🤘! I use it on all my projects 😄!

Now, I was updating the dependencies of one of my projects that still uses Node 10 and when I updated from `11.5.0` to `11.6.0`, I got an error saying the engine was incompatible.

I know Node 10 will reach end-of-life in 3 weeks, and makes sense you drop it now (I was actually considering the same thing on the project I was updating), but the issue is that doing it, is a breaking change, and if someone (like me) installs `leasot` using `^`, and stills supports Node 10, will get the same error. A minor release should always be backwards compatible.

You can close the issue, I just wanted to let you know.

**Comment by pgilad** [comment]
You're absolutely right @homer0  - should have been a major release 😊 Thanks for reporting this, but I'd prefer not to go deprecating versions as I'm afraid it'll create more harm than good.
I'll bump `leasot` majorly as well just in case
