### ISSUE TITLE
globbing/multiple files

### ISSUE THREAD

**Issue by ksmithut** [pgilad/leasot#2]
I see that you have commented in your code a todo to support multiple files in the cli (well, in your code, it's marked as `TOOD`). I would love to work on this feature if you haven't already started. Is there any reason or complication you ran into that stopped you from working on it?

**Comment by pgilad** [comment]
Hey - this is indeed a great feature to have! It's not hard to implement, but the challenge is deciding what exit codes and how to handle the multiple files.

For example if you have 2 files and 1 of them tries to use an unsupported extension, should you immediately exit with an error code, or just skip that file?

And also you will need to have a tracking for success/errors and to exit with the correct code in the end.

I would personally use either a async-each or a serial promise to resolve handling the files.

Anyway that kind of handling is great for a module on it's own. I could definitely use it on other projects that I have which have the same concepts for CLI (https://github.com/pgilad/check-constants/blob/master/bin/check-constants, https://github.com/pgilad/angular-html5/blob/master/bin/angular-html5.js etc...)

Feel free to add a PR for it, and hopefully if you can add a test for the CLI that would be awesome, and if it's in a module of it's own (or hopefully in the future) that would be best and most appreciated.

Gilad

**Comment by pgilad** [comment]
@ksmithut Hey - how is it going with this?

**Comment by ksmithut** [comment]
I've been pretty busy with my day job and school, but I think I'll finally have some time this afternoon to work on it :)

**Comment by pgilad** [comment]
great, LMK if you have any questions/issues

**Comment by ksmithut** [comment]
@pgilad This is turning out to be quite a bit more complicated than I thought. For some reason, I can get child_process.exec(File) to run anything. It just hangs. I'm thinking it might have to do with the way that mocha runs it's tests, but I haven't nailed it down just yet.

Also, with multiple files, I'm assuming we want to combine the reporting output?

**Comment by pgilad** [comment]
Hmm.
I would process and output every file in an async each series sort of way (as to not have mixed file report), and retain a final exit which would be:
- an error if any error occurred
- success otherwise

**Comment by ksmithut** [comment]
@pgilad I have an idea for how things should be processed, but I want to make sure that it's moving in the direction that will still be maintainable by you.

Right now, the `run` function in /bin/leasot.js is built to only handle one file, and manually calls `process.exit()`. In order to handle multiple files, I'm going to have to move the `process.exit`s elsewhere in order to support multiple files. Will that be okay?

**Comment by pgilad** [comment]
sure

**Comment by pgilad** [comment]
closed by f1254be46e23b4022d4c37cc8312851215a2d253
