### ISSUE TITLE
Support multiple keys in regex (in addition to TODO and FIXME)

### ISSUE THREAD

**Issue by kaldrenon** [pgilad/leasot#23]
Would love to be able to add other keys as arguments when I invoke `leasot`

I have a repo which includes "HACK" as a flag for temporary workarounds and in which we often add the dev's name to comments so we can look for who should help or work on a to-do.

Would love to be able to do `leasot -k hack,kaldrenon app/**/*.js` and get output for HACK, TODO, FIXME, and kaldrenon.

Took a look at the code for this and it seems a little tricky because `lib/regex.js` doesn't provide an opportunity to manipulate the regex **before** it's required, and resolving that would change the whole require strategy for the parsers.

Thoughts?

**Comment by pgilad** [comment]
Great idea. I've got a pretty easy implementation in mind. Only concern (As with all things in CS) is what to name cli option :smile:

key?
type?
tag?
 
Ref http://en.wikipedia.org/wiki/Comment_%28computer_programming%29

**Comment by kaldrenon** [comment]
It seems like tag is the best choice, since that has some history in this usage and is also a common pattern in other areas.

Right now `-t` is claimed as the short flag for `--filetype` -- I would vote for making `-f` the flag for that and using `-t/--tags` for tagging, but if you want to make a non-breaking change, I'd probably use `-g/--tags`

**Comment by pgilad** [comment]
@kaldrenon Did you try the new version? Did it work correctly?
I ended up with `--tags` or `-T` :smile:

**Comment by kaldrenon** [comment]
Looks good!

I'm wondering if it might be cool to also allow for excluding the defaults (so I can see *only* the tags I listed), but that would probably be another flag like `--skip-default` or `-s`.

Happy with it how it is, though. Thanks!
