### ISSUE TITLE
Allow HTML files

### ISSUE THREAD

**Issue by binarykitchen** [pgilad/leasot#25]
```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: File: /.../videomail-client/examples/bad_browser.html - Extension .html is not supported
```

You know, you can write inline JS in HTML files and in my case, there are some TODO remarks. So I think, HTML files should be allowed.

**Comment by binarykitchen** [comment]
Moved in here from https://github.com/pgilad/gulp-todo/issues/38

**Comment by pgilad** [comment]
Html files have 3 possible comment types in them:
- html
- js
- css

I'm contemplating if it's worth to try to juggle those comments in a multi-filetype sort of file (such as html).

On the other hand, if it's just js comments inside an html file, you can force the filetype in the cli with the option `--filetype` or using the programmatic `extension` option in https://github.com/pgilad/leasot#parseextension-contents-filename-customtags

**Comment by binarykitchen** [comment]
Hmm, forcing the filetype? I could but this makes things complicated because I am using gulp-todo here and do not want to be reminded about the filetype.

**Comment by binarykitchen** [comment]
hello?

**Comment by pgilad** [comment]
Sorry, been kind of busy. I would just add an HTML file support and support html, js and css style comments... PR is definitely welcome!

**Comment by binarykitchen** [comment]
just wanted to check - i am very busy either but would welcome such a change ...

**Comment by dkebler** [comment]
Was kinda wondering why leasot did support html out of the box being ubiquitous file format.   Go templates use html files so need it for more than just straight html.

Bit of a JS noob but I can try putting together a PR.  Should be as easy as copying a another similar parser and making a few changes no?

As to where to put it 
html comments  should be added to default.parser don't you think?? instead of separate file.

**Comment by dkebler** [comment]
Ah, default parser won't work that just for / and the like, but I think I can just add htm, htm extensions to existing twig parser as that's the same syntax.

**Comment by dkebler** [comment]
That was too easy.  PR has been made although I have some error in parser-spec that I don't understand how to fix (very nooby at test assertions, don't know much about mocha).

**Comment by pgilad** [comment]
Closed via https://github.com/pgilad/leasot/pull/32
