### ISSUE TITLE
@todo not TODO

### ISSUE THREAD

**Issue by thalesfsp** [pgilad/leasot#3]
It's possible to grab the default JSDoc3 "@todo" instead of "TODO:"?

Thanks!

**Comment by pgilad** [comment]
I think it's possible to allow the `@` as a prefix. You are welcome to add a PR for it, and it can be used only in `js` files (or coffescript etc.) so that it won't break things for other file types

**Comment by pgilad** [comment]
done!

**Comment by thalesfsp** [comment]
Perfect! Amazing!
PS: You bumped the version (Patch)?
Cheers!
