### ISSUE TITLE
Assign task

### ISSUE THREAD

**Issue by Tudes** [pgilad/leasot#31]
Having a task assignment column for contributors/developers would be interesting. Any thoughts on that?
![To Do table](https://cloud.githubusercontent.com/assets/2559394/9102149/5fcb0f4a-3bef-11e5-884c-0cecc7c46592.png)

Eg:
```
//TODO: Inject the TODO list into README.md --@name
```
or
```
//TODO: Inject the TODO list into README.md --#name
```

**Comment by pgilad** [comment]
Adding more functionality will result in this module being more complicated than I would like. I can see future requests for date parsing, JIRA issue parsing etc...

Thus supporting this will have to be via external plugin/module that is opt-in.

This is the structure of the comment after parsing:
https://github.com/pgilad/leasot/blob/master/lib/utils/comments.js#L18-L23

As you can see, comment `text` can be re parsed again for any extra metadata you want.

I would use this module programmatically, and add a custom reporter. You can copy the `markdown` reporter and modify it to output exactly the columns you want.

Let me know if you need any help with that... But as far as Leasot goes, I'm leaning towards not adding extra functionality that isn't covered by base, unless it's through custom reporters/parsers
