### ISSUE TITLE
Add support for the R language

### ISSUE THREAD

**Issue by TPreece101** [pgilad/leasot#322]
I'm thinking of making a PR to add support for `.R` files. They syntax in R for comments is just `# <comment>` and no multiline comment support so I'm thinking that `coffeeParser` will work well.

From looking at the library it seems like I need to do the following:

- [x] Add a `'.R'` property to the `parsersDb` in `src/lib/parsers.ts`
- [x] Add a test file to `tests/fixtures/`
- [x] Add a test to `tests/parser-spec.ts`
- [x] Add an entry to `media/supported-languages.md`

It would be great if you could let me know if I'm missing anything else that would need to be done. Are there any contribution guidelines anywhere? I had a look but I couldn't see anything, but I could be missing something 😅

**Comment by TPreece101** [comment]
Here is my PR: https://github.com/pgilad/leasot/pull/323

Let me know if I've missed anything 😁

**Comment by pgilad** [comment]
Looks good thanks!
