### ISSUE TITLE
Non-comment todo's (maybe feature request)

### ISSUE THREAD

**Issue by bard** [pgilad/leasot#337]
I often signal todo's via tests instead of comments, e.g. in JavaScript with jest or vitest:

```js
describe('calculator', () => {
  test.todo('adds numbers');
})
```

Is there a way of having those show up in `leasot`'s output?

**Comment by pgilad** [comment]
Hey, thanks for this. I don't think this works ATM but shouldn't be hard to do. Leasot work on regex parsing, you could create a special parser for this case, and you can extend this locally to work for you.

That said I no longer maintain this, but if you feel this is something common feel free to add a PR
