### ISSUE TITLE
Use "table" package instead of "text-table"

### ISSUE THREAD

**Issue by gajus** [pgilad/leasot#36]
https://github.com/gajus/table package is a very modular, well documented and well tested module/function for generating text tables. It allows granular customisation of how table contents is aligned, text wrapping, text truncation, border style and text padding.

If accepted, I will happily create a PR.

**Comment by pgilad** [comment]
This is just to update the `table` reporter?
What are the benefits that will be added over the existing behavior?

If this isn't a life-changer, I can accept a PR for a `table2` reporter which can be an alternative (or another reporter name to your liking)

**Comment by pgilad** [comment]
Thanks for the comemnt, @gajus if you feel like adding a PR feel free, but currently closing this
