### ISSUE TITLE
Erb should use the same parser as EJS.

### ISSUE THREAD

**Issue by zeroedin** [pgilad/leasot#42]
From this commit: https://github.com/pgilad/leasot/commit/6e3996dc9257aa0fb212a5d7a6aadb8debcc4ec3 `.erb` files are apparently being parsed by the `twigParser.js`.  

IMHO this is incorrect in the sense that both `<!-- comment -->` and `<%# comment %>` patterns are correct for a ruby erb file depending on the context.  `ejsParser.js` is already setup with both these patterns.  

However, I'm not sure how you are planning to organize these parsers.  Are you using their comment styles or the languages.  EJS obviously is not a Ruby based language so should ERB have it's own parser or is it ok in the framework of how you are building things to rely on a parser with the same patterns?

With that said I can make a PR to fix however you feel is appropriate.

**Comment by pgilad** [comment]
So are you saying `erb` should use the `ejsParser` ?

**Comment by zeroedin** [comment]
What I am saying is the comment patterns in `ejsParser.js` matches the same patterns erb files use, so yes in all practicality it should.  

However, for some reason that feels dirty to me, but on the other hand having a `erbParser.js` that is essentially a clone of `ejsParser.js` also does :)  Either way doesn't matter to me in the long run as long as it works.

**Comment by pgilad** [comment]
alright, then lets have the erbParser use the ejs one, no? A PR is highly welcomed!
