### ISSUE TITLE
exclude glob?

### ISSUE THREAD

**Issue by dkebler** [pgilad/leasot#50]
I don't see an exclude glob in the CLI so assuming there is none.
In my case I have an "off" subdirectory in a a lib directory that's excluded/ignored by requireall and I want leasot to do that as well.

**Comment by dkebler** [comment]
see my post in #48 for another use case issue

**Comment by pgilad** [comment]
This is for the cli only?

**Comment by pgilad** [comment]
Yeah an ignore/s pattern for cli is a much needed option.. feel free to add a PR!
