### ISSUE TITLE
add cson parser

### ISSUE THREAD

**Issue by dkebler** [pgilad/leasot#51]
add cson parser -   I'll do this PR when I get a chance just making an issue as a reminder

**Comment by dkebler** [comment]
no need for special parser just need to a cson as ext of coffee parser (works with -A).  That;s an easy PR

**Comment by pgilad** [comment]
Awesome! Awaiting the PR

**Comment by dkebler** [comment]
thx for doing this...been busy

**Comment by pgilad** [comment]
No problem
