### ISSUE TITLE
Support for filters

### ISSUE THREAD

**Issue by maximilianschmitt** [pgilad/leasot#52]
I think this is a really cool tool. Would be great if we could have a filter option to, for example, only show `TODO`s or show only `NOTE` and `XXX`.

Best,
Max

**Comment by pgilad** [comment]
Are you using it programmatically or via the cli?

**Comment by maximilianschmitt** [comment]
I'm using it via the CLI. :)

**Comment by pgilad** [comment]
I think the reporters could be extracted so they can just receive a json stream and output it to anything else.
That way you can act on the intermediately output of `leasot`:
```bash
$ leasot **/*.js | jq '.[] | select(.type == "TODO")' | leasot-reporter --reporter=markdown
```

Or something like that. That can enable you to do anything with the json stream that you wanted and basically use the reporters as you wish.

What do you think?

**Comment by maximilianschmitt** [comment]
Sounds pretty neat! What do you think about just doing something like `leasot **/*.js --only=todo,note`?

**Comment by pgilad** [comment]
That's good, but then we would have to support an unlimited use cases (for example show only todos from files with line 10+, or show todos that have text that contains "urgent", etc..)

This is why I'd rather let the user have full control of the filter, and that will require extracting the reporters

**Comment by pgilad** [comment]
Finally got around to implementing that, use this pattern:
```sh
$ leasot tests/**/*.styl --reporter json | jq 'map(select(.kind == "TODO"))' | leasot-reporter
```

**Comment by maximilianschmitt** [comment]
Wow, that was quick. Thanks a lot! :)
