### ISSUE TITLE
Support Hyperlink for Markdown reporter

### ISSUE THREAD

**Issue by pmunin** [pgilad/leasot#53]
It'd be awesome to have ability of generating a hyperlink to a file using some template/base specified in parameters. Right now it's just a file path.

**Comment by pgilad** [comment]
Great idea but I'm not sure I want to break backwards compatibility for the current markdown reporter. Perhaps a `markdown2` reporter?

**Comment by pmunin** [comment]
Maybe it does not have to break it - and expose it as additional parameter?

**Comment by pgilad** [comment]
Feel free to add a PR

**Comment by pgilad** [comment]
Closing this, feel free to add a PR
