### ISSUE TITLE
Optionally prevent `exit 1` when there are todos (so it doesn't break the build)

### ISSUE THREAD

**Issue by renatoargh** [pgilad/leasot#56]
Currently `leasot` will `exit 1` if there are TODOs so it will always break the build when running on CI server (see [this line](https://github.com/pgilad/leasot/blob/8eb86298b1c594d11f0f787802c014112667108d/lib/cli.js#L49)) - Yes, I am running `leasot` during the build process to log TODOs to the project website. 

I think that being able to pass a flag to always `exit 0` would be ideal.

thanks for the great work by the way! :)

**Comment by pgilad** [comment]
Yeah I agree a flag could be nice, any good ideas for a name?

**Comment by renatoargh** [comment]
First thing that comes to my mind is;

`leasot -0` and `leasot --always-0` 

Also, for symmetry, we could provide `leasot -1` or `leasot --always-1`

**Comment by pgilad** [comment]
BTW you know you can make `leasot` error code safe by using:
`leasot **/*.js || true` ?

**Comment by renatoargh** [comment]
hey @pgilad that worked for me, thanks a lot! fell free to close the issue if you think that implementing this is flag is no longer needed. all the best

**Comment by pgilad** [comment]
Well, If anyone else requests it I'll re-open.. Glad you're enjoying the tool!
