### ISSUE TITLE
Globbing does not work recursively

### ISSUE THREAD

**Issue by chapati23** [pgilad/leasot#60]
Not sure if that's expected behavior or not but i expected `leasot app/**/*.js` to also surface TODOs in `/app/sub/folder/deep/index.js`

It seems the glob explicitly refers to the given depth (e.g. app/**/* will only dig one folder-level into app and not go any deeper)

is that the correct behavior?

**Comment by pgilad** [comment]
I think your shell might expand that, can you try with quotes:
`leasot 'app/**/*.js'` ?

As you can see [here](https://github.com/pgilad/leasot/blob/master/lib/cli.js#L57-L61) everything is getting fed to `globby` so it should expand patterns

**Comment by chapati23** [comment]
Hehe, that was a tricky one. You're right, my shell _did_ automatically expand the stars. Using quotes works as expected, thank you.
