### ISSUE TITLE
Vue support issue

### ISSUE THREAD

**Issue by tyler36** [pgilad/leasot#63]
First, thanks for this useful software. It's a great way to generate automatic reports.

I'm having problems with VUE files. Given the follow example file, I would suspect it to find 3 TODOs. However, it only finds the ```<!-- TODO: Vue Template -->```

```
<template type="text/html">
    <!-- TODO: Vue Template -->
    <div class="container">
        <h1>Example</h1>
    </div>
</template>

<style type="text/css" lang="scss">
    // TODO: Vue CSS
</style>

<script type="text/javascript">
    /* TODO: Vue javascript */
    export default {
    };
</script>
```

If I move the blocks around, it still only sees the ```<!-- TODO: Vue Template -->```. If I add a ```<!---->``` style comment to the ```style``` or ```script``` section, it will find them. 

Is there support for multi-styled comments in Vue files? [Or perhaps a problem with my style]

OS: Win10 & Ubuntu 16.04.2

**Comment by pgilad** [comment]
If you notice `.vue` file have possible included files:
https://github.com/pgilad/leasot/blob/master/lib/parsers.js#L50

So you need to use the:
`    -I, --inline-files                   parse possible inline files`

in the cli to parse inline files.

Let me know if that solves it.

**Comment by tyler36** [comment]
Yeah, that works fine. Missed the switch. :(

Also works with with the 'todo-webpack-plugin' now that its been updated too.
