### ISSUE TITLE
Can't run from git-hook

### ISSUE THREAD

**Issue by friday** [pgilad/leasot#65]
If I put this in my .git/hooks/pre-commit:
```bash
node_modules/.bin/leasot "path/to/file.js"
```

I get this when I try to commit:
```js
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1431:5)
    at getFiletype (.../node_modules/leasot/lib/cli.js:13:30)
    at parseContentSync (.../node_modules/leasot/lib/cli.js:19:15)
    at .../node_modules/leasot/lib/cli.js:94:25
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The same thing also happens if I install leasot globally and replace the above with `leasot "path/to/file.js"`.

I can still run the script successfully with `.git/hooks/pre-commit`, which is strange, because git hooks are run as the same user doing the commit/push etc.

**Comment by friday** [comment]
Also getting the same error with either
```bash
cat path/to/file.js | leasot
cat path/to/file.js | leasot -t '.js'
```

**Comment by pgilad** [comment]
Thanks a lot @friday, that was definitely a critical bug. Fixed the function and added some unit-tests to hopefully prevent this in the future. Cheers for reporting this!

**Comment by pgilad** [comment]
https://github.com/pgilad/leasot/commit/f109ed70b728dee9e9a506b8f5ba3a0b873b3005

**Comment by friday** [comment]
Thanks for the great attitude and work :)

**Comment by friday** [comment]
I'm not getting the error any more, but I'm also not getting any todos unless I pipe:

```bash
#!/bin/bash
node_modules/.bin/leasot app/controllers/api.js
cat app/controllers/api.js | node_modules/.bin/leasot
```

```bash
 ✔ No todos/fixmes found

unknown file
  line 22   TODO  abcd
  line 34   TODO  fix this!

 ✖ 2 todos/fixmes found
```

Same problem (via git hook/tty, but not if I run the script directly)

**Comment by pgilad** [comment]
What is the way you currently use it?
```sh
#!/bin/bash
node_modules/.bin/leasot app/controllers/api.js
```
 ?

**Comment by friday** [comment]
That's not how I actually use it. I just tried to give you info that you could easily reproduce.

My intention is to show any todo comments added when you commit, as a reminder in case you meant to do them as part of the commit.

I just added this, which does exactly that:
```bash
git diff --staged | sed '/^+/!d' | sed 's .  ' | node_modules/.bin/leasot
if [ $? -ne 0 ]; then
	echo "Maybe you 'todid' them and forgot the comment(s), or you meant to 'todo' them as part of this commit?"
	echo "(note that the file name and line numbers won't be accurate)"
fi
```

Example output:

```
unknown file
  line 3  TODO  abcd
  line 4  TODO  fix this!

 ✖ 2 todos/fixmes found
Maybe you 'todid' them and forgot the comment(s), or you still need to 'todo' them?
(note that the file name and line numbers won't be accurate)
```

It works fine, apart from getting the file name and line number wrong (which is not a leasot issue since I'm piping a modified diff, not a file).

The problem mentioned above happened when I used a different approach where I would loop through all staged files and run through leasot individually. This is what I'm already doing for linting. It would look something like this:

```bash
for file in $(git diff --cached --name-only | grep -E '\.(js|jsx)$')
do
	node_modules/.bin/leasot "$file"
done
```

I hope that answers the question?

**Comment by pgilad** [comment]
Ok thanks a lot for helping me debug this. I found that that when running `leasot` through git hook node.js is thinking that it's running in !isTTY mode (i.e pipe) so that leasot expects contents to be piped in, but in this case there were files passed as arguments.

The solution is to always check if files were passed as arguments and use them, otherwise fallback to default behavior.

Thanks again!

**Comment by friday** [comment]
Works perfectly! Thanks for fixing this so fast! :)
