### ISSUE TITLE
Add support for .sql files

### ISSUE THREAD

**Issue by mickeypearce** [pgilad/leasot#66]
Would love to see support for .sql files `(-- and /* */). `

Or maybe to add a multi parser option to "associateExtWithParser" function.
Example. 
`'{.sql': {parserName: ['defaultParser', 'haskellParser']}} `

**Comment by pgilad** [comment]
Excellent idea! Feel free to add a PR

**Comment by mickeypearce** [comment]
Ok, I will.

Looks that it only needs to add a rest parameter to "parsers" variable in parsers.js to support multi parser option.

`[line: 101] var parsers = [...originalParser.parserName];`

Well designed! :+1:

**Comment by pgilad** [comment]
Dont forget to update the readme and add a test case as well :)

**Comment by pgilad** [comment]
Fixed by 95ad72114c2c668b7210d24fc474243fd0e13306
