### ISSUE TITLE
Failing tests on Windows at comments line number 

### ISSUE THREAD

**Issue by mickeypearce** [pgilad/leasot#67]
Anyone else experience failing tests on Windows with block line comments - wrong line number ? (apart from #45 issue)
Example:
```
2) parsing stylus parse block line comments:

      AssertionError: expected 9 to be 5
      + expected - actual

      -9
      +5
```

**Comment by pgilad** [comment]
Would appreciate any help on windows debugging as possible (I'm on Mac and Ubuntu).. Especially for #45 which has been a long living issue

**Comment by SeanSobey** [comment]
I think I found the problem, the library used to adjust line numbers [get-line-from-pos](https://github.com/pgilad/get-line-from-pos) does this:
```js
function getLineFromPos(str, pos) {
        if (pos === 0) {
            return 1;
        }
        //adjust for negative pos
        if (pos < 0) {
            pos = str.length + pos;
        }
        var lines = str.substr(0, pos).match(/[\n\r]/g);
        return lines ? lines.length + 1 : 1;
};
```
On windows each line ends in `\r\n` so that regex actually doubles the line number since it matches once for `\r` and `\n`.

I replaced `getLineFromPos` with one based on [eol](https://www.npmjs.com/package/eol):
```js
function getLineFromPos(str, pos) {
    if (pos === 0) {
        return 1;
    }
    //adjust for negative pos
    if (pos < 0) {
        pos = str.length + pos;
    }
    var lines = eol.split(str.substr(0, pos));
    return lines.length;
}
```

And now it works correctly

**Comment by SeanSobey** [comment]
There were also other places using hard coded `\n\` that needed to be replaced, which can also be done using `eol`, for example, the parsers:

```js
return function parse(contents, file) {
        var comments = [];

        contents.split('\n').forEach(function (line, index) {
```
to
```js
return function parse(contents, file) {
        var comments = [];

        eol.split(contents).forEach(function (line, index) {
```
Also some specs in `cli-spec.js` had hard coded epxectations for strings printed in [log-symbols](https://www.npmjs.com/package/log-symbols), but it has windows fallbacks which were different

**Comment by pgilad** [comment]
Hopefully fixed by @SeanSobey
