### ISSUE TITLE
Github reporter

### ISSUE THREAD

**Issue by M-Zuber** [pgilad/leasot#72]
I set out to write a tool that will take any `TODO`s in a code base and create a GH issue per each one (with options ect., can go into them as needed).
But had a thought, that if it would not be out of the scope of this tool, to just create a reporter that can do it instead of an entirely new tool.

Thoughts and opnions?

**Comment by pgilad** [comment]
I think an external reporter is the way to go, see:
https://github.com/pgilad/leasot/blob/master/lib/reporters.js#L20

I'd be happy to link and recommend it!
