### ISSUE TITLE
No way to warn only when in npm task

### ISSUE THREAD

**Issue by kodikos** [pgilad/leasot#75]
If you put this in an npm task it always fails if there are todo's. This is a little opinionated, as I just want to be reminded that I have todo's and what they are, not that it should interrupt my build process. Do you know of any workaround, or would this be a code fix to add a --warn-only option?

**Comment by pgilad** [comment]
`"todos": "leasot app/**/*.js || true"`

Will gladly accept a PR for updating the readme on this!
