### ISSUE TITLE
Give more complete example of using leasot from code with glob some directory and get correct report

### ISSUE THREAD

**Issue by lgordey** [pgilad/leasot#80]
In `Readme.md` you have only 1 example of 1 file.
It's nor really very usefull.

What I mean: 
In `node.js` I can copy string from example like `"leasot src/**/*.js"` - and thats it!
It's already work and I just need small configuration fixes with some parts of it like glob mask or ignoring directories.

On the other hand, we have an example in `js` code with parsing one file.

```
var contents = fs.readFileSync('./contents.js', 'utf8');
// get the filetype of the file, or force a special parser
var filetype = path.extname('./contents.js');
// add file for better reporting
var file = 'contents.js';
var todos = leasot.parse({ ext: filetype, content: contents, fileName: file });
```
So I really need to type some template code to make it works on all my project, like `cli` did.

I think it will be very usefull to have an example that makes the same result as `cli`.
With glob and etc.

Thanks for awesome project, btw 👍

**Comment by lgordey** [comment]
Actually it does not matter
excuse me 😄

**Comment by jameelmoses** [comment]
I'm experiencing the same issue and would greatly appreciate a programmatic example with a glob

**Comment by pgilad** [comment]
@jameelmoses I think the usage of the cli can be helpful, feel free to add a PR to improve the readme, and I'll try to add it if you don't when I have free time
https://github.com/pgilad/leasot/blob/master/src/cli/cli.ts#L52-L59
