### ISSUE TITLE
vscode markdown link line numbers not working

### ISSUE THREAD

**Issue by SeanSobey** [pgilad/leasot#85]
After generating the report using the VSCode reporter it generates lines like so:
```
| [src\ServerConfig.ts](src\ServerConfig.ts#301) | 301 | compress?
```
They appear clickable, but the line numbers do not reference properly. I found [this](https://github.com/Microsoft/vscode/issues/8223#issuecomment-266374037) comment on a vscode issue which had an 'L' before the number and indeed after adding it the reference works:
```
| [src\ServerConfig.ts](src\ServerConfig.ts#L301) | 301 | compress?
```

**Comment by pgilad** [comment]
Awesome, want to take a stab at fixing the code?
https://github.com/pgilad/leasot/blob/master/lib/reporters/vscode.js#L16

**Comment by SeanSobey** [comment]
Sure, seems like it would be fairly simple to add.

I did have to fix the other windows related issues first to be able to run the tests :)

**Comment by pgilad** [comment]
Closed by https://github.com/pgilad/leasot/commit/cb765bc2cae89c7afb064438cf12558e243a1745
