### ISSUE TITLE
Add Recursive Globing 

### ISSUE THREAD

**Issue by sid2934** [pgilad/leasot#86]
I could not find a way to allow the glob to recursively enter sub-directories.

My use case is a C# project that has ToDos in varying levels of depth in the directory and I have to run the command line tool as many times as levels of depth I have. I could be totally wrong admittedly.

**Comment by pgilad** [comment]
Try to use `leasot 'src/**/*.cs'` (wrap the glob with quotes to prevent the shell from expanding it)
