### ISSUE TITLE
Dedicated javascript/typescript parser

### ISSUE THREAD

**Issue by SeanSobey** [pgilad/leasot#90]
This is mostly to be able to handle inline comments, by using a specialized parser like esprima/babel/espree, similar to the proposal in [issue 62](https://github.com/pgilad/leasot/issues/62), but in a language-specific way.

I have [branch](https://github.com/SeanSobey/leasot/tree/javascriptParser) on my fork with a working prototype. I switched the defaultParser for js files to the javascriptParser and the only test that is failing is the vue.vue file related one. I believe this is not really a bug because the test is expected a `js` parser to handle a whole `vue` file. It may be necessary to scope the parser to just `<script>` tags for example but that is quite a big rework I think.

In any case maybe this javascriptParser can be included as an optional one to be used by `options.associateParser`? Its quite a bit better at javascript/typescript since it is based on the Abstract Syntax Tree, also it can be configured to use a number of [extractors](https://www.npmjs.com/package/extract-comments#extractors) including custom ones.

**In the process of this I also saw that `uniq` in `parsers.js` is incorrect and should be using `uniqWith`, see [this](https://github.com/SeanSobey/leasot/commit/d09d37e40f0c667f36fda4a4a76e98fba2245a4c) commit.**

**Comment by pgilad** [comment]
I started this project with a dedicated parser for javascript, but then when expanded to other languages I didn't want the project to start installing a gazillion dependencies where are you needed is a simple regex comment extractor.

We can perhaps build a platform for using an external parser and passing the comments to `leasot-reporter`, but I don't want to go with the route of dedicated parsers, even though they are great and they can handle 100% of the cases, while `leasot` can sometimes fail (positively or negatively)

**Comment by pgilad** [comment]
Re: `uniq`, would love a fix on that

**Comment by SeanSobey** [comment]
Your consideration for the large number of dependencies dedicated parsers will introduce makes total sense.

Maybe as you suggest, we could go the the route of allowing custom parsers, something like [this](https://github.com/pgilad/leasot/compare/master...SeanSobey:custom-parsers).

PS: I created a [PR](https://github.com/pgilad/leasot/pull/91) for the uniq fix.

**Comment by renatoargh** [comment]
Hey guys, can someone point me to the proper way of catching inline comments? I am suing TS
