### ISSUE TITLE
Throw TypeError when appropriate

### ISSUE THREAD

**Issue by TheDancingCode** [pgilad/leasot#95]
Whenever you throw an error because a value is not of the expected type, it's more specific and therefore more informative to throw a `TypeError`. Plain `Error` constructs aren't wrong per se, just more generic.

This already happens in a few places, like [lib/reportes.js#L32](https://github.com/pgilad/leasot/blob/8eb86298b1c594d11f0f787802c014112667108d/lib/reporters.js#L32), but not in other cases, like [lib/reporters/markdown.js#26](https://github.com/pgilad/leasot/blob/283a29c2a9f8056012665d8164fd3ecdf110e180/lib/reporters/markdown.js#L26).

**Comment by pgilad** [comment]
I agree 😄 . Feel free to add a PR for it
