### ISSUE TITLE
Feature Request: Multiple Line Todos

### ISSUE THREAD

**Issue by alexhagen** [pgilad/leasot#99]
Hello,

It would be quite useful to be able to do multiple line TODOs.  This would allow me to have longer todo tasks, but not violate PEP8 or other code readability standards.

Of course, I will defer to you on the syntax, however either of these would be interesting for python:

```python
# TODO: Here is a very very long comment where I'm really effusive on exactly what
# I need to do in the todo.
```

or

```python
# TODO: Another way of doing multiple line comments could be by allowing a line
# TODO2: parameter after the todo keyword so that you could have multiple
# TODO3: multiple line comments after one another
```

I can make a pull request, but this seems like this might be an easy fix, so if you know how to quickly do it and have the time, it would be faster than me going through the overhead of forking and learning the codebase.  Thanks,

Alex Hagen

**Comment by ecarlisle** [comment]
@alexhagen ,
It looks like multiline for Python has been include via [triple-quoted strings](https://www.python.org/dev/peps/pep-0008/#string-quotes). 

https://github.com/pgilad/leasot/blob/master/lib/parsers/pythonParser.js#L7

I know that approach is not every Python programmer's preference`</alliteration>` but for whatever reason that's the convention chosen for that parser.

One solution could be to create an additional `# TODO` multiline regex pattern for that parser and add an additional loop like the existing one:
https://github.com/pgilad/leasot/blob/master/lib/parsers/pythonParser.js#L24-L32
Your first example would most likely be the easier one to implement. You could make a capture group for the content on each line, making sure to filter out the beginning `#` on each line. Then concatenate the captures to make a single comment string.

Another option would be to replace to take that or a similar approach and use it as a custom parser:
https://github.com/pgilad/leasot#custom-parsers

Food for thought? :-)

**Comment by alexhagen** [comment]
Thanks - I'll definitely go with the triple quoted strings for now.
